filepath = r'C:\Users\danpo\Desktop\rvs\src\Engine\Src\UnMeshInstance.cpp'
with open(filepath, 'r', encoding='utf-8-sig') as f:
    lines = f.readlines()

# Each entry: (unique_search_string_in_line, macro_to_insert)
insertions = [
    # --- ULodMeshInstance ---
    ('FMeshAnimSeq * ULodMeshInstance::GetAnimSeq(FName)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('void ULodMeshInstance::Serialize(FArchive& Ar)',
     'IMPL_GHIDRA_APPROX("Engine.dll", 0x103c6ff0, "simplified to UObject::Serialize; render bounds regenerated on load")'),
    ('void ULodMeshInstance::SetActor(AActor * a)',
     'IMPL_INFERRED("accessor; no Ghidra address")'),
    ('void ULodMeshInstance::SetMesh(UMesh * m)',
     'IMPL_INFERRED("accessor; no Ghidra address")'),
    ('void ULodMeshInstance::SetStatus(int s)',
     'IMPL_INFERRED("accessor; no Ghidra address")'),
    ('AActor * ULodMeshInstance::GetActor()',
     'IMPL_INFERRED("accessor; no Ghidra address")'),
    ('void ULodMeshInstance::GetFrame(AActor *,FLevelSceneNode *,FVector *,int,int &,DWORD)',
     'IMPL_GHIDRA("Engine.dll", 0x14730)'),
    ('UMaterial * ULodMeshInstance::GetMaterial(int,AActor *)',
     'IMPL_GHIDRA("Engine.dll", 0x6c990)'),
    ('UMesh * ULodMeshInstance::GetMesh()',
     'IMPL_INFERRED("accessor; no Ghidra address")'),
    ('void ULodMeshInstance::GetMeshVerts(AActor *,FVector *,int,int &)',
     'IMPL_GHIDRA("Engine.dll", 0x14770)'),
    ('INT ULodMeshInstance::GetStatus()',
     'IMPL_INFERRED("accessor; no Ghidra address")'),

    # --- UMeshInstance ---
    ('int UMeshInstance::StopAnimating(int)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('int UMeshInstance::UpdateAnimation(float)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('void UMeshInstance::Render(FDynamicActor *,FLevelSceneNode *,TList<FDynamicLight *> *,FRenderInterface *)',
     'IMPL_GHIDRA("Engine.dll", 0x14770)'),
    ('void UMeshInstance::SetActor(AActor *)',
     'IMPL_INTENTIONALLY_EMPTY("Retail (3b): base no-op; subclasses override")'),
    ('void UMeshInstance::SetAnimFrame(int,float)',
     'IMPL_INTENTIONALLY_EMPTY("Retail (3b): base no-op; subclasses override")'),
    ('void UMeshInstance::SetMesh(UMesh *)',
     'IMPL_INTENTIONALLY_EMPTY("Retail (3b): base no-op; subclasses override")'),
    ('void UMeshInstance::SetScale(FVector)',
     'IMPL_INTENTIONALLY_EMPTY("Retail (3b): base no-op; subclasses override")'),
    ('void UMeshInstance::SetStatus(int)',
     'IMPL_GHIDRA("Engine.dll", 0x1651d0)'),
    ('int UMeshInstance::LineCheck(FCheckResult &Hit,AActor *Owner,FVector End,FVector Start,FVector Extent,DWORD ExtraNodeFlags,DWORD TraceFlags)',
     'IMPL_GHIDRA("Engine.dll", 0x14650)'),
    ('int UMeshInstance::PlayAnim(int,FName,float,float,int,int,int)',
     'IMPL_GHIDRA("Engine.dll", 0x14580)'),
    ('int UMeshInstance::PointCheck(FCheckResult &Hit,AActor *Owner,FVector Point,FVector Extent,DWORD TraceFlags)',
     'IMPL_GHIDRA("Engine.dll", 0x145f0)'),
    ('int UMeshInstance::AnimForcePose(FName,float,float,int)',
     'IMPL_GHIDRA("Engine.dll", 0x33a0)'),
    ('float UMeshInstance::AnimGetFrameCount(void *)',
     'IMPL_GHIDRA("Engine.dll", 0x14590)'),
    ('FName UMeshInstance::AnimGetGroup(void *)',
     'IMPL_INFERRED("no Ghidra address; returns NAME_None")'),
    ('FName UMeshInstance::AnimGetName(void *)',
     'IMPL_INFERRED("no Ghidra address; returns NAME_None")'),
    ('int UMeshInstance::AnimGetNotifyCount(void *)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('UAnimNotify * UMeshInstance::AnimGetNotifyObject(void *,int)',
     'IMPL_GHIDRA("Engine.dll", 0x6c990)'),
    ('const TCHAR* UMeshInstance::AnimGetNotifyText(void *,int)',
     'IMPL_INFERRED("Ghidra: returns empty string; no explicit address")'),
    ('float UMeshInstance::AnimGetNotifyTime(void *,int)',
     'IMPL_GHIDRA("Engine.dll", 0x145b0)'),
    ('float UMeshInstance::AnimGetRate(void *)',
     'IMPL_INFERRED("Ghidra: default rate is 15.0; no explicit address")'),
    ('int UMeshInstance::AnimIsInGroup(void *,FName)',
     'IMPL_GHIDRA("Engine.dll", 0x6c990)'),
    ('int UMeshInstance::AnimStopLooping(int)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('void UMeshInstance::ClearChannel(int)',
     'IMPL_INTENTIONALLY_EMPTY("Retail (3b): base no-op; subclasses override")'),
    ('int UMeshInstance::FreezeAnimAt(float,int)',
     'IMPL_GHIDRA("Engine.dll", 0x6c990)'),
    ('float UMeshInstance::GetActiveAnimFrame(int)',
     'IMPL_GHIDRA("Engine.dll", 0x14590)'),
    ('float UMeshInstance::GetActiveAnimRate(int)',
     'IMPL_GHIDRA("Engine.dll", 0x14590)'),
    ('FName UMeshInstance::GetActiveAnimSequence(int)',
     'IMPL_INFERRED("no Ghidra address; returns NAME_None")'),
    ('AActor * UMeshInstance::GetActor()',
     'IMPL_GHIDRA("Engine.dll", 0x114310)'),
    ('int UMeshInstance::GetAnimCount()',
     'IMPL_GHIDRA("Engine.dll", 0x114310)'),
    ('void * UMeshInstance::GetAnimIndexed(int)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('void * UMeshInstance::GetAnimNamed(FName)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('FBox UMeshInstance::GetCollisionBoundingBox(const AActor* Owner)',
     'IMPL_INFERRED("Retail: 32b delegate; no explicit address")'),
    ('void UMeshInstance::GetFrame(AActor *,FLevelSceneNode *,FVector *,int,int &,DWORD)',
     'IMPL_GHIDRA("Engine.dll", 0x14730)'),
    ('UMaterial * UMeshInstance::GetMaterial(int,AActor *)',
     'IMPL_GHIDRA("Engine.dll", 0x6c990)'),
    ('UMesh * UMeshInstance::GetMesh()',
     'IMPL_GHIDRA("Engine.dll", 0x114310)'),
    ('FBox UMeshInstance::GetRenderBoundingBox(const AActor* Owner)',
     'IMPL_INFERRED("Retail: 32b delegate; no explicit address")'),
    ('FSphere UMeshInstance::GetRenderBoundingSphere(const AActor* Owner)',
     'IMPL_INFERRED("Retail: 32b delegate; no explicit address")'),
    ('int UMeshInstance::GetStatus()',
     'IMPL_GHIDRA("Engine.dll", 0x114310)'),
    ('int UMeshInstance::IsAnimating(int)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('int UMeshInstance::IsAnimLooping(int)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('int UMeshInstance::IsAnimPastLastFrame(int)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),
    ('int UMeshInstance::IsAnimTweening(int)',
     'IMPL_GHIDRA("Engine.dll", 0x4720)'),

    # --- USkeletalMeshInstance ---
    ('int USkeletalMeshInstance::TraceHeadHit(FCheckResult& Hit, FVector const& Start, FVector const& End, FVector const& DirNorm, float const& Extent)',
     'IMPL_TODO("Retail 0x12FF20; complex cylinder/head-bone trace; returning 0 as safe stub")'),
    ('void USkeletalMeshInstance::UpdateBlendAlpha(INT Channel, float Alpha, float DeltaTime)',
     'IMPL_GHIDRA("Engine.dll", 0x134EF0)'),
    ('int USkeletalMeshInstance::ValidateAnimChannel(INT Channel)',
     'IMPL_GHIDRA("Engine.dll", 0x130F40)'),
    ('void USkeletalMeshInstance::SetAnimRate(INT Channel, FLOAT Rate)',
     'IMPL_GHIDRA("Engine.dll", 0x134A90)'),
    ('void USkeletalMeshInstance::SetAnimSequence(INT Channel, FName SeqName)',
     'IMPL_GHIDRA_APPROX("Engine.dll", 0x134FC0, "DIVERGENCE: vtable FindAnimObject call approximated for anim-slot lookup")'),
    ('void USkeletalMeshInstance::SetBlendAlpha(INT Channel, FLOAT Alpha)',
     'IMPL_INFERRED("Retail: 145b SEH; no explicit address; faithfully decompiled")'),
    ('int USkeletalMeshInstance::SetBlendParams(INT Channel, FLOAT Alpha, FLOAT UScale, FLOAT VScale, FName BoneRef, INT bBlend)',
     'IMPL_GHIDRA("Engine.dll", 0x1326B0)'),
    ('int USkeletalMeshInstance::SetBoneDirection(FName,FRotator,FVector,float)',
     'IMPL_GHIDRA_APPROX("Engine.dll", 0x131A90, "partial implementation; bone direction logic unimplemented")'),
    ('int USkeletalMeshInstance::SetBoneLocation(FName BoneName, FVector Location, FLOAT Scale)',
     'IMPL_GHIDRA("Engine.dll", 0x1317A0)'),
    ('int USkeletalMeshInstance::SetBonePosition(FName BoneName, FRotator Rot, FVector Loc, FLOAT Scale)',
     'IMPL_GHIDRA("Engine.dll", 0x131BA0)'),
    ('int USkeletalMeshInstance::SetBoneRotation(FName BoneName, FRotator NewRot, INT bNotifyOwner, FLOAT BlendTarget, FLOAT BlendSpeed)',
     'IMPL_GHIDRA("Engine.dll", 0x131890)'),
    ('int USkeletalMeshInstance::SetBoneScale(INT BoneChannel, FLOAT Scale, FName BoneName)',
     'IMPL_GHIDRA("Engine.dll", 0x131620)'),
    ('int USkeletalMeshInstance::SetSkelAnim(UMeshAnimation* Anim, USkeletalMesh* Mesh)',
     'IMPL_INFERRED("faithfully decompiled; no explicit Ghidra address")'),
    ('int USkeletalMeshInstance::LockRootMotion(INT Mode, INT /*Unused*/)',
     'IMPL_INFERRED("faithfully decompiled; no explicit Ghidra address")'),
    ('int USkeletalMeshInstance::MatchRefBone(FName BoneName)',
     'IMPL_GHIDRA("Engine.dll", 0x130D40)'),
    ('void USkeletalMeshInstance::BlendToAlpha(INT Channel, FLOAT BlendAlpha, FLOAT DeltaTime)',
     'IMPL_GHIDRA("Engine.dll", 0x1351B0)'),
    ('void USkeletalMeshInstance::BuildPivotsList()',
     'IMPL_TODO("Retail 0x1361a0; builds bone pivot list; needs full decompilation")'),
    ('void USkeletalMeshInstance::ClearSkelAnims()',
     'IMPL_GHIDRA("Engine.dll", 0x13D860)'),
    ('void USkeletalMeshInstance::CopyAnimation(INT Src, INT Dst)',
     'IMPL_GHIDRA("Engine.dll", 0x134980)'),
    ('void USkeletalMeshInstance::DrawCollisionCylinders(FSceneNode *)',
     'IMPL_TODO("Retail 0x10436390; debug cylinder rendering; needs implementation")'),
    ('int USkeletalMeshInstance::EnableChannelNotify(INT Channel, INT bEnable)',
     'IMPL_GHIDRA("Engine.dll", 0x1338B0)'),
    ('void USkeletalMeshInstance::ForceAnimRate(INT Channel, FLOAT Rate)',
     'IMPL_GHIDRA("Engine.dll", 0x134B80)'),
    ('int USkeletalMeshInstance::GetAnimChannelCount()',
     'IMPL_INFERRED("Retail: 12b; no explicit address")'),
    ('float USkeletalMeshInstance::GetAnimFrame(INT Channel)',
     'IMPL_INFERRED("Retail: 93b SEH; no explicit address")'),
    ('float USkeletalMeshInstance::GetAnimRateOnChannel(INT Channel)',
     'IMPL_GHIDRA("Engine.dll", 0x135B20)'),
    ('FName USkeletalMeshInstance::GetAnimSequence(INT Channel)',
     'IMPL_INFERRED("Retail: 98b SEH; no explicit address")'),
    ('float USkeletalMeshInstance::GetBlendAlpha(INT Channel)',
     'IMPL_INFERRED("Retail: 93b SEH; no explicit address")'),
    ('FCoords USkeletalMeshInstance::GetBoneCoords(DWORD,int)',
     'IMPL_TODO("Needs Ghidra analysis; returns identity FCoords")'),
    ('int USkeletalMeshInstance::GetBoneCylinder(int BoneIndex, FCylinder& Cyl)',
     'IMPL_GHIDRA_APPROX("Engine.dll", 0x133990, "DIVERGENCE: m_fCylindersRadius table not yet populated from binary")'),
    ('FName USkeletalMeshInstance::GetBoneName(FName BoneName)',
     'IMPL_GHIDRA("Engine.dll", 0x133680)'),
    ('FRotator USkeletalMeshInstance::GetBoneRotation(DWORD boneIndex, INT Space)',
     'IMPL_GHIDRA("Engine.dll", 0x133520)'),
    ('FRotator USkeletalMeshInstance::GetBoneRotation(FName BoneName, INT Space)',
     'IMPL_GHIDRA("Engine.dll", 0x133610)'),
    ('FVector USkeletalMeshInstance::GetRootLocation()',
     'IMPL_GHIDRA("Engine.dll", 0x12F8F0)'),
    ('FVector USkeletalMeshInstance::GetRootLocationDelta()',
     'IMPL_GHIDRA("Engine.dll", 0x133790)'),
    ('FRotator USkeletalMeshInstance::GetRootRotation()',
     'IMPL_GHIDRA("Engine.dll", 0x12F950)'),
    ('FRotator USkeletalMeshInstance::GetRootRotationDelta()',
     'IMPL_GHIDRA("Engine.dll", 0x12F9B0)'),
    ('FCoords USkeletalMeshInstance::GetTagCoords(FName TagName)',
     'IMPL_GHIDRA("Engine.dll", 0x135BF0)'),
    ('FCoords USkeletalMeshInstance::GetTagPosition(FName TagName)',
     'IMPL_GHIDRA("Engine.dll", 0x133700)'),
    ('int USkeletalMeshInstance::StopAnimating(int bClearAll)',
     'IMPL_GHIDRA("Engine.dll", 0x135800)'),
    ('int USkeletalMeshInstance::UpdateAnimation(FLOAT DeltaTime)',
     'IMPL_GHIDRA("Engine.dll", 0x132d10)'),
    ('void USkeletalMeshInstance::Render(FDynamicActor *,FLevelSceneNode *,TList<FDynamicLight *> *,FRenderInterface *)',
     'IMPL_TODO("Retail 0x174f70; full skeletal mesh rendering pipeline; needs implementation")'),
    ('void USkeletalMeshInstance::Serialize(FArchive& Ar)',
     'IMPL_GHIDRA_APPROX("Engine.dll", 0x10438750, "simplified to base Serialize; per-field data regenerated at runtime")'),
    ('void USkeletalMeshInstance::SetAnimFrame(INT Channel, FLOAT Frame)',
     'IMPL_INFERRED("Retail: 96b SEH; no explicit address")'),
    ('void USkeletalMeshInstance::SetMesh(UMesh* NewMesh)',
     'IMPL_GHIDRA("Engine.dll", 0x135AA0)'),
    ('void USkeletalMeshInstance::SetScale(FVector Scale)',
     'IMPL_GHIDRA("Engine.dll", 0x130E40)'),
    ('int USkeletalMeshInstance::LineCheck(FCheckResult& Hit, AActor* Owner, FVector End, FVector Start, FVector Extent, DWORD ExtraNodeFlags, DWORD TraceFlags)',
     'IMPL_GHIDRA("Engine.dll", 0x133b50)'),
    ('void USkeletalMeshInstance::MeshSkinVertsCallback(void *)',
     'IMPL_TODO("Retail 0x13da50; GPU-skinning transform FUN_10438ce0 identity unresolved")'),
    ('int USkeletalMeshInstance::PlayAnim(INT Channel, FName SeqName, FLOAT Rate, FLOAT TweenTime, INT bLooping, INT bLoopLast, INT bIdle)',
     'IMPL_GHIDRA("Engine.dll", 0x131D50)'),
    ('int USkeletalMeshInstance::ActiveVertStreamSize()',
     'IMPL_GHIDRA("Engine.dll", 0x133960)'),
    ('void USkeletalMeshInstance::ActualizeAnimLinkups()',
     'IMPL_GHIDRA("Engine.dll", 0x135A30)'),
    ('int USkeletalMeshInstance::AnimForcePose(FName SeqName, FLOAT Frame, FLOAT Rate, INT Channel)',
     'IMPL_GHIDRA("Engine.dll", 0x132ac0)'),
    ('float USkeletalMeshInstance::AnimGetFrameCount(void* Channel)',
     'IMPL_INFERRED("Retail: 14b; no explicit address")'),
    ('FName USkeletalMeshInstance::AnimGetGroup(void* Channel)',
     'IMPL_INFERRED("Retail: 34b; no explicit address")'),
    ('FName USkeletalMeshInstance::AnimGetName(void* Channel)',
     'IMPL_INFERRED("Retail: 19b; no explicit address")'),
    ('int USkeletalMeshInstance::AnimGetNotifyCount(void* Channel)',
     'IMPL_INFERRED("Retail: 20b; no explicit address")'),
    ('UAnimNotify * USkeletalMeshInstance::AnimGetNotifyObject(void* Channel, int notifyIndex)',
     'IMPL_INFERRED("Retail: 25b; no explicit address")'),
    ('const TCHAR* USkeletalMeshInstance::AnimGetNotifyText(void* Channel, INT notifyIndex)',
     'IMPL_INFERRED("Retail: 31b; no explicit address")'),
    ('float USkeletalMeshInstance::AnimGetNotifyTime(void* Channel, INT notifyIndex)',
     'IMPL_INFERRED("Retail: 24b; no explicit address")'),
    ('float USkeletalMeshInstance::AnimGetRate(void* Channel)',
     'IMPL_INFERRED("Retail: 14b; no explicit address")'),
    ('int USkeletalMeshInstance::AnimIsInGroup(void* Channel, FName GroupName)',
     'IMPL_INFERRED("Retail: 37b; direct call not fully reconstructed")'),
    ('int USkeletalMeshInstance::AnimStopLooping(INT channel)',
     'IMPL_INFERRED("Retail: 104b SEH; no explicit address")'),
    ('void USkeletalMeshInstance::ClearChannel(INT Channel)',
     'IMPL_GHIDRA("Engine.dll", 0x132500)'),
    ('UMeshAnimation* USkeletalMeshInstance::CurrentSkelAnim(INT Channel)',
     'IMPL_INFERRED("no Ghidra reference")'),
    ('void USkeletalMeshInstance::Destroy()',
     'IMPL_GHIDRA("Engine.dll", 0x12f640)'),
    ('UMeshAnimation* USkeletalMeshInstance::FindAnimObjectForSequence(FName SeqName)',
     'IMPL_GHIDRA("Engine.dll", 0x132A50)'),
    ('int USkeletalMeshInstance::FreezeAnimAt(FLOAT Frame, INT Channel)',
     'IMPL_GHIDRA("Engine.dll", 0x131040)'),
    ('float USkeletalMeshInstance::GetActiveAnimFrame(INT Channel)',
     'IMPL_INFERRED("Retail: 93b SEH; no explicit address")'),
    ('float USkeletalMeshInstance::GetActiveAnimRate(INT Channel)',
     'IMPL_INFERRED("Retail: 93b SEH; no explicit address")'),
    ('FName USkeletalMeshInstance::GetActiveAnimSequence(INT Channel)',
     'IMPL_INFERRED("Retail: 98b SEH; no explicit address")'),
    ('int USkeletalMeshInstance::GetAnimCount()',
     'IMPL_GHIDRA("Engine.dll", 0x132810)'),
    ('void * USkeletalMeshInstance::GetAnimIndexed(INT Index)',
     'IMPL_INFERRED("Retail: 88b; no explicit address")'),
    ('void* USkeletalMeshInstance::GetAnimNamed(FName SeqName)',
     'IMPL_GHIDRA("Engine.dll", 0x1328D0)'),
    ('void USkeletalMeshInstance::GetFrame(AActor *,FLevelSceneNode *,FVector *,int,int &,DWORD)',
     'IMPL_TODO("Retail 0x10439f40; Ghidra decompilation failed; needs re-analysis")'),
    ('UMaterial * USkeletalMeshInstance::GetMaterial(int materialIndex, AActor* Actor)',
     'IMPL_INFERRED("Retail: 49b; no explicit address")'),
    ('void USkeletalMeshInstance::GetMeshVerts(AActor *,FVector *,int,int &)',
     'IMPL_TODO("Retail 0x13d8e0; FUN_10438ce0 identity unresolved")'),
    ('FBox USkeletalMeshInstance::GetRenderBoundingBox(const AActor*)',
     'IMPL_INFERRED("Retail: 33b; no explicit address")'),
    ('FSphere USkeletalMeshInstance::GetRenderBoundingSphere(const AActor*)',
     'IMPL_INFERRED("Retail: 31b; no explicit address")'),
    ('int USkeletalMeshInstance::IsAnimating(int Channel)',
     'IMPL_GHIDRA("Engine.dll", 0x130FB0)'),
    ('int USkeletalMeshInstance::IsAnimLooping(INT Channel)',
     'IMPL_INFERRED("Retail: 93b SEH; no explicit address")'),
    ('int USkeletalMeshInstance::IsAnimPastLastFrame(INT Channel)',
     'IMPL_INFERRED("Retail: 111b SEH; no explicit address")'),
    ('int USkeletalMeshInstance::IsAnimTweening(int Channel)',
     'IMPL_GHIDRA("Engine.dll", 0x131110)'),
    ('int USkeletalMeshInstance::WasSkeletonUpdated()',
     'IMPL_GHIDRA("Engine.dll", 0x12F8B0)'),
    ('void USkeletalMeshInstance::MeshBuildBounds()',
     'IMPL_TODO("Retail 0x141f40; bounding box/sphere iteration; needs implementation")'),
    ('FMatrix USkeletalMeshInstance::MeshToWorld()',
     'IMPL_INFERRED("no Ghidra reference; returns FMatrix::Identity")'),

    # --- UVertMeshInstance ---
    ('FMeshAnimSeq * UVertMeshInstance::GetAnimSeq(FName Name)',
     'IMPL_INFERRED("Retail: ~90b; no explicit address")'),
    ('int UVertMeshInstance::StopAnimating(INT Channel)',
     'IMPL_INFERRED("Retail: 15b; no explicit address")'),
    ('int UVertMeshInstance::UpdateAnimation(FLOAT DeltaTime)',
     'IMPL_GHIDRA("Engine.dll", 0x172950)'),
    ('void UVertMeshInstance::Render(FDynamicActor *,FLevelSceneNode *,TList<FDynamicLight *> *,FRenderInterface *)',
     'IMPL_TODO("Retail 0x174f70; full vertex mesh rendering pipeline; needs implementation")'),
    ('void UVertMeshInstance::Serialize(FArchive &)',
     'IMPL_TODO("Retail 0x174730; TArray serialize helper FUN_10321a80 unresolved")'),
    ('void UVertMeshInstance::SetAnimFrame(int, float Frame)',
     'IMPL_INFERRED("Retail: 13b; no explicit address")'),
    ('void UVertMeshInstance::SetScale(FVector Scale)',
     'IMPL_GHIDRA("Engine.dll", 0x173500)'),
    ('int UVertMeshInstance::PlayAnim(INT Channel, FName SeqName, FLOAT Rate, FLOAT TweenTime, INT bLooping, INT bLoopLast, INT bIdle)',
     'IMPL_GHIDRA("Engine.dll", 0x172d40)'),
    ('int UVertMeshInstance::AnimForcePose(FName SeqName, FLOAT Frame, FLOAT Rate, INT Channel)',
     'IMPL_GHIDRA("Engine.dll", 0x1724f0)'),
    ('float UVertMeshInstance::AnimGetFrameCount(void* Channel)',
     'IMPL_INFERRED("Retail: 10b; no explicit address")'),
    ('FName UVertMeshInstance::AnimGetGroup(void* Channel)',
     'IMPL_INFERRED("Retail: 34b; no explicit address")'),
    ('FName UVertMeshInstance::AnimGetName(void* Channel)',
     'IMPL_INFERRED("Retail: 15b; no explicit address")'),
    ('int UVertMeshInstance::AnimGetNotifyCount(void* Channel)',
     'IMPL_INFERRED("Retail: 16b; no explicit address")'),
    ('UAnimNotify * UVertMeshInstance::AnimGetNotifyObject(void* Channel, int notifyIndex)',
     'IMPL_INFERRED("Retail: 21b; no explicit address")'),
    ('const TCHAR* UVertMeshInstance::AnimGetNotifyText(void* Channel, INT notifyIndex)',
     'IMPL_INFERRED("Retail: 27b; no explicit address")'),
    ('float UVertMeshInstance::AnimGetNotifyTime(void* Channel, INT notifyIndex)',
     'IMPL_INFERRED("Retail: 20b; no explicit address")'),
    ('float UVertMeshInstance::AnimGetRate(void* Channel)',
     'IMPL_INFERRED("Retail: 10b; no explicit address")'),
    ('int UVertMeshInstance::AnimIsInGroup(void*, FName)',
     'IMPL_INFERRED("Retail: 48b; sub-call unresolved")'),
    ('int UVertMeshInstance::AnimStopLooping(int)',
     'IMPL_INFERRED("Retail: 22b; no explicit address")'),
    ('float UVertMeshInstance::GetActiveAnimFrame(INT Channel)',
     'IMPL_INFERRED("Retail: 17b; no explicit address")'),
    ('float UVertMeshInstance::GetActiveAnimRate(INT Channel)',
     'IMPL_INFERRED("Retail: 17b; no explicit address")'),
    ('FName UVertMeshInstance::GetActiveAnimSequence(int sequenceChannelIndex)',
     'IMPL_INFERRED("Retail: 23b; no explicit address")'),
    ('int UVertMeshInstance::GetAnimCount()',
     'IMPL_INFERRED("Retail: 18b; no explicit address")'),
    ('void * UVertMeshInstance::GetAnimIndexed(INT Index)',
     'IMPL_INFERRED("Retail: 34b; no explicit address")'),
    ('void * UVertMeshInstance::GetAnimNamed(FName Name)',
     'IMPL_INFERRED("Retail: ~144b; no explicit address")'),
    ('void UVertMeshInstance::GetFrame(AActor *,FLevelSceneNode *,FVector *,int,int &,DWORD)',
     'IMPL_TODO("Retail 0x10473c20; transforms vertex mesh frames; needs implementation")'),
    ('UMaterial * UVertMeshInstance::GetMaterial(int materialIndex, AActor* Actor)',
     'IMPL_INFERRED("Retail: 49b; no explicit address")'),
    ('void UVertMeshInstance::GetMeshVerts(AActor *,FVector *,int,int &)',
     'IMPL_TODO("Retail: vertex transform; needs implementation")'),
    ('FBox UVertMeshInstance::GetRenderBoundingBox(const AActor* Owner)',
     'IMPL_INFERRED("Retail: 33b; no explicit address")'),
    ('FSphere UVertMeshInstance::GetRenderBoundingSphere(const AActor*)',
     'IMPL_INFERRED("Retail: 84b SEH; no explicit address")'),
    ('int UVertMeshInstance::IsAnimating(int Channel)',
     'IMPL_GHIDRA("Engine.dll", 0x1725d0)'),
    ('int UVertMeshInstance::IsAnimLooping(int)',
     'IMPL_INFERRED("Retail: 9b; no explicit address")'),
    ('int UVertMeshInstance::IsAnimPastLastFrame(int)',
     'IMPL_INFERRED("Retail: 31b; no explicit address")'),
    ('int UVertMeshInstance::IsAnimTweening(int)',
     'IMPL_INFERRED("Retail: 9b; no explicit address")'),
    ('void UVertMeshInstance::MeshBuildBounds()',
     'IMPL_TODO("Retail 0x174850; bounding box/sphere over vertex frames; needs implementation")'),
    ('FMatrix UVertMeshInstance::MeshToWorld()',
     'IMPL_INFERRED("no Ghidra reference; returns FMatrix::Identity")'),

    # --- UMeshInstance bottom (near end of file) ---
    ('void UMeshInstance::MeshBuildBounds() {}',
     'IMPL_TODO("Needs Ghidra analysis")'),
    ('FMatrix UMeshInstance::MeshToWorld() { // Retail: 36b.',
     'IMPL_INFERRED("Retail: 36b; returns FMatrix::Identity")'),
]

# Find line indices for each insertion (searching from top for first match)
insertions_with_idx = []
for search, macro in insertions:
    found_idx = None
    for i, line in enumerate(lines):
        if search in line:
            found_idx = i
            break
    if found_idx is None:
        print(f"ERROR: Not found: {search!r}")
        raise SystemExit(1)
    insertions_with_idx.append((found_idx, macro, search))

# Sort by line index DESCENDING so we insert from bottom to top
# (so earlier insertions don't shift later line numbers)
insertions_with_idx.sort(key=lambda x: x[0], reverse=True)

# Perform insertions
for line_idx, macro, search in insertions_with_idx:
    # Detect indentation of the target line
    target_line = lines[line_idx]
    indent = len(target_line) - len(target_line.lstrip())
    indent_str = target_line[:indent]
    macro_line = indent_str + macro + '\n'
    lines.insert(line_idx, macro_line)

# Write back (no BOM since we read with utf-8-sig which strips it)
with open(filepath, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print(f"Done! Inserted {len(insertions_with_idx)} macros.")
print(f"New line count: {len(lines)}")
