/*=============================================================================
  EngineBatchImpl3.cpp: Round 3 batch implementations.
  Auto-generated by gen_impl4.py
=============================================================================*/

#include "EnginePrivate.h"


// Forward declarations for types used by generated stubs
struct FBspNode;
struct FBspSection;
struct FBspVertex;
struct FPosNormTexData;
struct FSkinVertex;
struct FStaticMeshBatcherVertex;
struct FStaticMeshCollisionNode;
struct FStaticMeshCollisionTriangle;
struct FStaticMeshLightInfo;
struct FStaticMeshMaterial;
struct FStaticMeshSection;
struct FStaticMeshTriangle;
struct FStaticMeshUV;
struct FStaticMeshVertex;
struct FStaticMeshVertexStream;
struct FTerrainVertex;
struct FTerrainVertexStream;
struct FUV2Data;
struct FUntransformedVertex;
struct FProjectorRelativeRenderInfo;
struct FOrientation { BYTE Pad[16]; FOrientation& operator=(FOrientation) { return *this; } int operator!=(const FOrientation&) const { return 0; } };
struct FHitCause;
struct HHitProxy;
struct FRebuildOptions { BYTE Pad[256]; };
struct _KarmaGlobals;
struct _McdGeometry;
struct McdGeomMan;
struct _KarmaTriListData;


/*-----------------------------------------------------------------------------
  Data definitions
-----------------------------------------------------------------------------*/

UEngine * g_pEngine = NULL;

int AVIRecording = 0;

FString FURL::DefaultHost;

FString FURL::DefaultLocalMap;

FString FURL::DefaultMap;

FString FURL::DefaultMapExt;

FString FURL::DefaultName;

FString FURL::DefaultPortal;

FString FURL::DefaultProtocol;

FString FURL::DefaultProtocolDescription;

FString FURL::DefaultSaveExt;

UAudioSubsystem * USound::Audio = NULL;

UClient * UTexture::__Client = NULL;

float * USkeletalMeshInstance::m_fCylindersRadius = NULL;

int * FCollisionHash::HashX = NULL;

int * FCollisionHash::HashY = NULL;

int * FCollisionHash::HashZ = NULL;

int FCollisionHash::CollisionTag = 0;

int FCollisionHash::Inited = 0;

int FURL::DefaultPort = 0;

_KarmaGlobals * KGData = NULL;


/*-----------------------------------------------------------------------------
  Implementations
-----------------------------------------------------------------------------*/

// ??6@YAAAVFArchive@@AAV0@AAVFAnimMeshVertexStream@@@Z
FArchive & operator<<(FArchive & p0, FAnimMeshVertexStream & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFBspNode@@@Z
FArchive & operator<<(FArchive & p0, FBspNode & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFBspSection@@@Z
FArchive & operator<<(FArchive & p0, FBspSection & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFBspSurf@@@Z
FArchive & operator<<(FArchive & p0, FBspSurf & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFBspVertexStream@@@Z
FArchive & operator<<(FArchive & p0, FBspVertexStream & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFLightMap@@@Z
FArchive & operator<<(FArchive & p0, FLightMap & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFLightMapTexture@@@Z
FArchive & operator<<(FArchive & p0, FLightMapTexture & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFPoly@@@Z
FArchive & operator<<(FArchive & p0, FPoly & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFRaw32BitIndexBuffer@@@Z
FArchive & operator<<(FArchive & p0, FRaw32BitIndexBuffer & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFRawColorStream@@@Z
FArchive & operator<<(FArchive & p0, FRawColorStream & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFRawIndexBuffer@@@Z
FArchive & operator<<(FArchive & p0, FRawIndexBuffer & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFSkinVertexStream@@@Z
FArchive & operator<<(FArchive & p0, FSkinVertexStream & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFStaticLightMapTexture@@@Z
FArchive & operator<<(FArchive & p0, FStaticLightMapTexture & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFStaticMeshBatcherVertex@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshBatcherVertex & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFStaticMeshLightInfo@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshLightInfo & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFStaticMeshMaterial@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshMaterial & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFStaticMeshSection@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshSection & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFStaticMeshUVStream@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshUVStream & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFStaticMeshVertexStream@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshVertexStream & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFTags@@@Z
FArchive & operator<<(FArchive & p0, FTags & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFTerrainVertexStream@@@Z
FArchive & operator<<(FArchive & p0, FTerrainVertexStream & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAVFURL@@@Z
FArchive & operator<<(FArchive & p0, FURL & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFBspVertex@@@Z
FArchive & operator<<(FArchive & p0, FBspVertex & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFPosNormTexData@@@Z
FArchive & operator<<(FArchive & p0, FPosNormTexData & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFProjectorRelativeRenderInfo@@@Z
FArchive & operator<<(FArchive & p0, FProjectorRelativeRenderInfo & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@PAUFProjectorRenderInfo@@@Z
FArchive & operator<<(FArchive & p0, FProjectorRenderInfo * p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFSkinVertex@@@Z
FArchive & operator<<(FArchive & p0, FSkinVertex & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFStaticMeshCollisionNode@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshCollisionNode & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFStaticMeshCollisionTriangle@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshCollisionTriangle & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFStaticMeshUV@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshUV & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFStaticMeshVertex@@@Z
FArchive & operator<<(FArchive & p0, FStaticMeshVertex & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFTerrainVertex@@@Z
FArchive & operator<<(FArchive & p0, FTerrainVertex & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFUV2Data@@@Z
FArchive & operator<<(FArchive & p0, FUV2Data & p1) { static FArchive dummy; return dummy; }

// ??6@YAAAVFArchive@@AAV0@AAUFUntransformedVertex@@@Z
FArchive & operator<<(FArchive & p0, FUntransformedVertex & p1) { static FArchive dummy; return dummy; }

// ?GNewCollisionHash@@YAPAVFCollisionHashBase@@XZ
FCollisionHashBase * GNewCollisionHash() { return NULL; }

// ?FGetHSV@@YA?AVFPlane@@EEE@Z
FPlane FGetHSV(BYTE p0, BYTE p1, BYTE p2) { return FPlane(); }

// ?GetFROTATOR@@YAHPBGAAVFRotator@@H@Z
int GetFROTATOR(const TCHAR* p0, FRotator & p1, int p2) { return 0; }

// ?GetFROTATOR@@YAHPBG0AAVFRotator@@H@Z
int GetFROTATOR(const TCHAR* p0, const TCHAR* p1, FRotator & p2, int p3) { return 0; }

// ?GetFVECTOR@@YAHPBGAAVFVector@@@Z
int GetFVECTOR(const TCHAR* p0, FVector & p1) { return 0; }

// ?GetFVECTOR@@YAHPBG0AAVFVector@@@Z
int GetFVECTOR(const TCHAR* p0, const TCHAR* p1, FVector & p2) { return 0; }

// ?GetSUBSTRING@@YAHPBG0PAGH@Z
int GetSUBSTRING(const TCHAR* p0, const TCHAR* p1, TCHAR* p2, int p3) { return 0; }

// ?getGameShutDown@@YAHXZ
int getGameShutDown() { return 0; }

// ?newPath@FPathBuilder@@AAEPAVANavigationPoint@@VFVector@@@Z
ANavigationPoint * FPathBuilder::newPath(FVector p0) { return NULL; }

// ?DistanceToHashPlane@FCollisionHash@@AAEMHMMH@Z
float FCollisionHash::DistanceToHashPlane(int p0, float p1, float p2, int p3) { return 0; }

// ?findNewFloor@APawn@@AAEHVFVector@@MMH@Z
int APawn::findNewFloor(FVector p0, float p1, float p2, int p3) { return 0; }

// ?TestReach@FPathBuilder@@AAEHVFVector@@0@Z
int FPathBuilder::TestReach(FVector p0, FVector p1) { return 0; }

// ?TestWalk@FPathBuilder@@AAEHVFVector@@UFCheckResult@@M@Z
int FPathBuilder::TestWalk(FVector p0, FCheckResult p1, float p2) { return 0; }

// ?ValidNode@FPathBuilder@@AAEHPAVANavigationPoint@@PAVAActor@@@Z
int FPathBuilder::ValidNode(ANavigationPoint * p0, AActor * p1) { return 0; }

// ?createPaths@FPathBuilder@@AAEHXZ
int FPathBuilder::createPaths() { return 0; }

// ?StoreActor@FOctreeNode@@AAEXPAVAActor@@PAVFCollisionOctree@@PBVFPlane@@@Z
void FOctreeNode::StoreActor(AActor * p0, FCollisionOctree * p1, FPlane const * p2) {}

// ?FindBlockingNormal@FPathBuilder@@AAEXAAVFVector@@@Z
void FPathBuilder::FindBlockingNormal(FVector & p0) {}

// ?Pass2From@FPathBuilder@@AAEXVFVector@@0M@Z
void FPathBuilder::Pass2From(FVector p0, FVector p1, float p2) {}

// ?SetPathCollision@FPathBuilder@@AAEXH@Z
void FPathBuilder::SetPathCollision(int p0) {}

// ?getScout@FPathBuilder@@AAEXXZ
void FPathBuilder::getScout() {}

// ?testPathsFrom@FPathBuilder@@AAEXVFVector@@@Z
void FPathBuilder::testPathsFrom(FVector p0) {}

// ?testPathwithRadius@FPathBuilder@@AAEXVFVector@@M@Z
void FPathBuilder::testPathwithRadius(FVector p0, float p1) {}

// ??0ECLipSynchData@@QAE@PAVUMeshInstance@@PAVUSound@@1PAVAActor@@@Z
ECLipSynchData::ECLipSynchData(UMeshInstance * p0, USound * p1, USound * p2, AActor * p3) {}

// ??0ECLipSynchData@@QAE@XZ
ECLipSynchData::ECLipSynchData() {}

// ??0FActorSceneNode@@QAE@PAVUViewport@@PAVAActor@@1VFVector@@VFRotator@@M@Z
FActorSceneNode::FActorSceneNode(UViewport * p0, AActor * p1, AActor * p2, FVector p3, FRotator p4, float p5) : FSceneNode((UViewport*)NULL) {}

// ??1FAnimMeshVertexStream@@QAE@XZ
FAnimMeshVertexStream::~FAnimMeshVertexStream() {}

// ??1FBspVertexStream@@QAE@XZ
FBspVertexStream::~FBspVertexStream() {}

// ??0FCameraSceneNode@@QAE@PAVUViewport@@PAVAActor@@VFVector@@VFRotator@@M@Z
FCameraSceneNode::FCameraSceneNode(UViewport * p0, AActor * p1, FVector p2, FRotator p3, float p4) : FSceneNode((UViewport*)NULL) {}

// ??1FCanvasUtil@@QAE@XZ
FCanvasUtil::~FCanvasUtil() {}

// ??0FCollisionHash@@QAE@ABV0@@Z
FCollisionHash::FCollisionHash(FCollisionHash const & p0) {}

// ??0FCollisionHash@@QAE@XZ
FCollisionHash::FCollisionHash() {}

// ??0FCollisionOctree@@QAE@ABV0@@Z
FCollisionOctree::FCollisionOctree(FCollisionOctree const & p0) {}

// ??0FCollisionOctree@@QAE@XZ
FCollisionOctree::FCollisionOctree() {}

// ??0FDirectionalLightMapSceneNode@@QAE@PAVUViewport@@PAVAActor@@AAVFBspSurf@@PAVFLightMap@@@Z
FDirectionalLightMapSceneNode::FDirectionalLightMapSceneNode(UViewport * p0, AActor * p1, FBspSurf & p2, FLightMap * p3) : FSceneNode((UViewport*)NULL) {}

// ??0FHitCause@@QAE@PAVFHitObserver@@PAVUViewport@@KMM@Z
FHitCause::FHitCause(FHitObserver * p0, UViewport * p1, DWORD p2, float p3, float p4) {}

// ??0FLevelSceneNode@@QAE@PAV0@HVFMatrix@@@Z
FLevelSceneNode::FLevelSceneNode(FLevelSceneNode * p0, int p1, FMatrix p2) : FSceneNode((UViewport*)NULL) {}

// ??0FLevelSceneNode@@QAE@ABV0@@Z
FLevelSceneNode::FLevelSceneNode(FLevelSceneNode const & p0) : FSceneNode((UViewport*)NULL) {}

// ??0FLevelSceneNode@@QAE@PAVUViewport@@@Z
FLevelSceneNode::FLevelSceneNode(UViewport * p0) : FSceneNode((UViewport*)NULL) {}

// ??1FLightMap@@QAE@XZ
FLightMap::~FLightMap() {}

// ??0FLightMapSceneNode@@QAE@PAVUViewport@@PAVAActor@@PAVFLightMap@@@Z
FLightMapSceneNode::FLightMapSceneNode(UViewport * p0, AActor * p1, FLightMap * p2) : FSceneNode((UViewport*)NULL) {}

// ??1FLightMapTexture@@QAE@XZ
FLightMapTexture::~FLightMapTexture() {}

// ??1FLineBatcher@@QAE@XZ
FLineBatcher::~FLineBatcher() {}

// ??0FMatineeTools@@QAE@ABV0@@Z
FMatineeTools::FMatineeTools(FMatineeTools const & p0) {}

// ??0FOctreeNode@@QAE@ABV0@@Z
FOctreeNode::FOctreeNode(FOctreeNode const & p0) {}

// ??0FOctreeNode@@QAE@XZ
FOctreeNode::FOctreeNode() {}

// ??1FOctreeNode@@QAE@XZ
FOctreeNode::~FOctreeNode() {}

// ??0FPointLightMapSceneNode@@QAE@PAVUViewport@@PAVAActor@@AAVFBspSurf@@PAVFLightMap@@HHHH@Z
FPointLightMapSceneNode::FPointLightMapSceneNode(UViewport * p0, AActor * p1, FBspSurf & p2, FLightMap * p3, int p4, int p5, int p6, int p7) : FSceneNode((UViewport*)NULL) {}

// ??0FPoly@@QAE@XZ
FPoly::FPoly() {}

// ??1FRaw32BitIndexBuffer@@QAE@XZ
FRaw32BitIndexBuffer::~FRaw32BitIndexBuffer() {}

// ??1FRawColorStream@@QAE@XZ
FRawColorStream::~FRawColorStream() {}

// ??1FRawIndexBuffer@@QAE@XZ
FRawIndexBuffer::~FRawIndexBuffer() {}

// ??0FRebuildTools@@QAE@ABV0@@Z
FRebuildTools::FRebuildTools(FRebuildTools const & p0) {}

// ??1FRebuildTools@@QAE@XZ
FRebuildTools::~FRebuildTools() {}

// ??0FRotatorF@@QAE@VFRotator@@@Z
FRotatorF::FRotatorF(FRotator p0) {}

// ??0FRotatorF@@QAE@MMM@Z
FRotatorF::FRotatorF(float p0, float p1, float p2) {}

// ??0FRotatorF@@QAE@XZ
FRotatorF::FRotatorF() {}

// ??0FSceneNode@@QAE@PAV0@@Z
FSceneNode::FSceneNode(FSceneNode * p0) {}

// ??0FSceneNode@@QAE@ABV0@@Z
FSceneNode::FSceneNode(FSceneNode const & p0) {}

// ??0FSceneNode@@QAE@PAVUViewport@@@Z
FSceneNode::FSceneNode(UViewport * p0) {}

// ??1FSkinVertexStream@@QAE@XZ
FSkinVertexStream::~FSkinVertexStream() {}

// ??0FStatGraph@@QAE@ABV0@@Z
FStatGraph::FStatGraph(FStatGraph const & p0) {}

// ??1FStatGraph@@QAE@XZ
FStatGraph::~FStatGraph() {}

// ??1FStaticLightMapTexture@@QAE@XZ
FStaticLightMapTexture::~FStaticLightMapTexture() {}

// ??1FStaticMeshUVStream@@QAE@XZ
FStaticMeshUVStream::~FStaticMeshUVStream() {}

// ??1FStaticMeshVertexStream@@QAE@XZ
FStaticMeshVertexStream::~FStaticMeshVertexStream() {}

// ??0FURL@@QAE@PAV0@PBGW4ETravelType@@@Z
FURL::FURL(FURL * p0, const TCHAR* p1, ETravelType p2) {}

// ??0FURL@@QAE@PBG@Z
FURL::FURL(const TCHAR* p0) {}

// ??0FWaveModInfo@@QAE@XZ
FWaveModInfo::FWaveModInfo() {}

// ?findEndAnchor@FSortedPathList@@QAEPAVANavigationPoint@@PAVAPawn@@PAVAActor@@VFVector@@H@Z
ANavigationPoint * FSortedPathList::findEndAnchor(APawn * p0, AActor * p1, FVector p2, int p3) { return NULL; }

// ?findStartAnchor@FSortedPathList@@QAEPAVANavigationPoint@@PAVAPawn@@@Z
ANavigationPoint * FSortedPathList::findStartAnchor(APawn * p0) { return NULL; }

// ?GetCurrent@FMatineeTools@@QAEPAVASceneManager@@XZ
ASceneManager * FMatineeTools::GetCurrent() { return NULL; }

// ?SetCurrent@FMatineeTools@@QAEPAVASceneManager@@PAVUEngine@@PAVULevel@@PAV2@@Z
ASceneManager * FMatineeTools::SetCurrent(UEngine * p0, ULevel * p1, ASceneManager * p2) { return NULL; }

// ?SetCurrent@FMatineeTools@@QAEPAVASceneManager@@PAVUEngine@@PAVULevel@@VFString@@@Z
ASceneManager * FMatineeTools::SetCurrent(UEngine * p0, ULevel * p1, FString p2) { return NULL; }

// ??4ECLipSynchData@@QAEAAV0@ABV0@@Z
ECLipSynchData & ECLipSynchData::operator=(ECLipSynchData const & p0) { static ECLipSynchData dummy; return dummy; }

// ??4FCollisionHash@@QAEAAV0@ABV0@@Z
FCollisionHash & FCollisionHash::operator=(FCollisionHash const & p0) { static FCollisionHash dummy; return dummy; }

// ??4FCollisionOctree@@QAEAAV0@ABV0@@Z
FCollisionOctree & FCollisionOctree::operator=(FCollisionOctree const & p0) { static FCollisionOctree dummy; return dummy; }

// ??4FOctreeNode@@QAEAAV0@ABV0@@Z
FOctreeNode & FOctreeNode::operator=(FOctreeNode const & p0) { static FOctreeNode dummy; return dummy; }

// ??4FPathBuilder@@QAEAAV0@ABV0@@Z
FPathBuilder & FPathBuilder::operator=(FPathBuilder const & p0) { static FPathBuilder dummy; return dummy; }

// ?Project@FSceneNode@@QAE?AVFPlane@@VFVector@@@Z
FPlane FSceneNode::Project(FVector p0) { return FPlane(); }

// ??4FPoly@@QAEAAV0@ABV0@@Z
FPoly & FPoly::operator=(FPoly const & p0) { static FPoly dummy; return dummy; }

// ?GetCurrent@FRebuildTools@@QAEPAVFRebuildOptions@@XZ
FRebuildOptions * FRebuildTools::GetCurrent() { return NULL; }

// ?GetFromName@FRebuildTools@@QAEPAVFRebuildOptions@@VFString@@@Z
FRebuildOptions * FRebuildTools::GetFromName(FString p0) { return NULL; }

// ?Save@FRebuildTools@@QAEPAVFRebuildOptions@@VFString@@@Z
FRebuildOptions * FRebuildTools::Save(FString p0) { return NULL; }

// ?Rotator@FRotatorF@@QAE?AVFRotator@@XZ
FRotator FRotatorF::Rotator() { return FRotator(); }

// ??4FRotatorF@@QAEAAV0@ABV0@@Z
FRotatorF & FRotatorF::operator=(FRotatorF const & p0) { static FRotatorF dummy; return dummy; }

// ??DFRotatorF@@QBE?AV0@M@Z
FRotatorF FRotatorF::operator*(float p0) const { return FRotatorF(); }

// ??XFRotatorF@@QAE?AV0@M@Z
FRotatorF FRotatorF::operator*=(float p0) { return FRotatorF(); }

// ??HFRotatorF@@QBE?AV0@V0@@Z
FRotatorF FRotatorF::operator+(FRotatorF p0) const { return FRotatorF(); }

// ??YFRotatorF@@QAE?AV0@V0@@Z
FRotatorF FRotatorF::operator+=(FRotatorF p0) { return FRotatorF(); }

// ??GFRotatorF@@QBE?AV0@V0@@Z
FRotatorF FRotatorF::operator-(FRotatorF p0) const { return FRotatorF(); }

// ??ZFRotatorF@@QAE?AV0@V0@@Z
FRotatorF FRotatorF::operator-=(FRotatorF p0) { return FRotatorF(); }

// ??4FStatGraph@@QAEAAV0@ABV0@@Z
FStatGraph & FStatGraph::operator=(FStatGraph const & p0) { static FStatGraph dummy; return dummy; }

// ?GetOrientationDesc@FMatineeTools@@QAE?AVFString@@H@Z
FString FMatineeTools::GetOrientationDesc(int p0) { return FString(); }

// ?String@FURL@@QBE?AVFString@@H@Z
FString FURL::String(int p0) const { return FString(); }

// ?GetTextureSize@FPoly@@QAE?AVFVector@@XZ
FVector FPoly::GetTextureSize() { return FVector(); }

// ?Vector@FRotatorF@@QAE?AVFVector@@XZ
FVector FRotatorF::Vector() { return FVector(); }

// ?Deproject@FSceneNode@@QAE?AVFVector@@VFPlane@@@Z
FVector FSceneNode::Deproject(FPlane p0) { return FVector(); }

// ??4FWaveModInfo@@QAEAAV0@ABV0@@Z
FWaveModInfo & FWaveModInfo::operator=(FWaveModInfo const & p0) { static FWaveModInfo dummy; return dummy; }

// ?GetCurrentAction@FMatineeTools@@QAEPAVUMatAction@@XZ
UMatAction * FMatineeTools::GetCurrentAction() { return NULL; }

// ?GetNextAction@FMatineeTools@@QAEPAVUMatAction@@PAVASceneManager@@PAV2@@Z
UMatAction * FMatineeTools::GetNextAction(ASceneManager * p0, UMatAction * p1) { return NULL; }

// ?GetNextMovementAction@FMatineeTools@@QAEPAVUMatAction@@PAVASceneManager@@PAV2@@Z
UMatAction * FMatineeTools::GetNextMovementAction(ASceneManager * p0, UMatAction * p1) { return NULL; }

// ?GetPrevAction@FMatineeTools@@QAEPAVUMatAction@@PAVASceneManager@@PAV2@@Z
UMatAction * FMatineeTools::GetPrevAction(ASceneManager * p0, UMatAction * p1) { return NULL; }

// ?SetCurrentAction@FMatineeTools@@QAEPAVUMatAction@@PAV2@@Z
UMatAction * FMatineeTools::SetCurrentAction(UMatAction * p0) { return NULL; }

// ?GetCurrentSubAction@FMatineeTools@@QAEPAVUMatSubAction@@XZ
UMatSubAction * FMatineeTools::GetCurrentSubAction() { return NULL; }

// ?SetCurrentSubAction@FMatineeTools@@QAEPAVUMatSubAction@@PAV2@@Z
UMatSubAction * FMatineeTools::SetCurrentSubAction(UMatSubAction * p0) { return NULL; }

// ?Area@FPoly@@QAEMXZ
float FPoly::Area() { return 0; }

// ?GetActionIdx@FMatineeTools@@QAEHPAVASceneManager@@PAVUMatAction@@@Z
int FMatineeTools::GetActionIdx(ASceneManager * p0, UMatAction * p1) { return 0; }

// ?GetPathStyle@FMatineeTools@@QAEHPAVUMatAction@@@Z
int FMatineeTools::GetPathStyle(UMatAction * p0) { return 0; }

// ?GetSubActionIdx@FMatineeTools@@QAEHPAVUMatSubAction@@@Z
int FMatineeTools::GetSubActionIdx(UMatSubAction * p0) { return 0; }

// ?buildPaths@FPathBuilder@@QAEHPAVULevel@@@Z
int FPathBuilder::buildPaths(ULevel * p0) { return 0; }

// ?removePaths@FPathBuilder@@QAEHPAVULevel@@@Z
int FPathBuilder::removePaths(ULevel * p0) { return 0; }

// ?CalcNormal@FPoly@@QAEHH@Z
int FPoly::CalcNormal(int p0) { return 0; }

// ?DoesLineIntersect@FPoly@@QAEHVFVector@@0PAV2@@Z
int FPoly::DoesLineIntersect(FVector p0, FVector p1, FVector * p2) { return 0; }

// ?Faces@FPoly@@QBEHABV1@@Z
int FPoly::Faces(FPoly const & p0) const { return 0; }

// ?Finalize@FPoly@@QAEHH@Z
int FPoly::Finalize(int p0) { return 0; }

// ?Fix@FPoly@@QAEHXZ
int FPoly::Fix() { return 0; }

// ?IsBackfaced@FPoly@@QBEHABVFVector@@@Z
int FPoly::IsBackfaced(FVector const & p0) const { return 0; }

// ?IsCoplanar@FPoly@@QBEHABV1@@Z
int FPoly::IsCoplanar(FPoly const & p0) const { return 0; }

// ?OnPlane@FPoly@@QAEHVFVector@@@Z
int FPoly::OnPlane(FVector p0) { return 0; }

// ?OnPoly@FPoly@@QAEHVFVector@@@Z
int FPoly::OnPoly(FVector p0) { return 0; }

// ?Split@FPoly@@QAEHABVFVector@@0H@Z
int FPoly::Split(FVector const & p0, FVector const & p1, int p2) { return 0; }

// ?SplitPrecise@FPoly@@QAEHABVFVector@@0H@Z
int FPoly::SplitPrecise(FVector const & p0, FVector const & p1, int p2) { return 0; }

// ?SplitWithNode@FPoly@@QBEHPBVUModel@@HPAV1@1H@Z
int FPoly::SplitWithNode(UModel const * p0, int p1, FPoly * p2, FPoly * p3, int p4) const { return 0; }

// ?SplitWithPlane@FPoly@@QBEHABVFVector@@0PAV1@1H@Z
int FPoly::SplitWithPlane(FVector const & p0, FVector const & p1, FPoly * p2, FPoly * p3, int p4) const { return 0; }

// ?SplitWithPlaneFast@FPoly@@QBEHVFPlane@@PAV1@1@Z
int FPoly::SplitWithPlaneFast(FPlane p0, FPoly * p1, FPoly * p2) const { return 0; }

// ?SplitWithPlaneFastPrecise@FPoly@@QBEHVFPlane@@PAV1@1@Z
int FPoly::SplitWithPlaneFastPrecise(FPlane p0, FPoly * p1, FPoly * p2) const { return 0; }

// ??9FPoly@@QAEHV0@@Z
int FPoly::operator!=(FPoly p0) { return 0; }

// ??8FPoly@@QAEHV0@@Z
int FPoly::operator==(FPoly p0) { return 0; }

// ?GetIdxFromName@FRebuildTools@@QAEHVFString@@@Z
int FRebuildTools::GetIdxFromName(FString p0) { return 0; }

// ?Exec@FStatGraph@@QAEHPBGAAVFOutputDevice@@@Z
int FStatGraph::Exec(const TCHAR* p0, FOutputDevice & p1) { return 0; }

// ?HasOption@FURL@@QBEHPBG@Z
int FURL::HasOption(const TCHAR* p0) const { return 0; }

// ?IsInternal@FURL@@QBEHXZ
int FURL::IsInternal() const { return 0; }

// ?IsLocalInternal@FURL@@QBEHXZ
int FURL::IsLocalInternal() const { return 0; }

// ??8FURL@@QBEHABV0@@Z
int FURL::operator==(FURL const & p0) const { return 0; }

// ?ReadWaveInfo@FWaveModInfo@@QAEHAAV?$TArray@E@@@Z
int FWaveModInfo::ReadWaveInfo(TArray<BYTE> & p0) { return 0; }

// ?UpdateWaveData@FWaveModInfo@@QAEHAAV?$TArray@E@@@Z
int FWaveModInfo::UpdateWaveData(TArray<BYTE> & p0) { return 0; }

// ?StaticExit@FURL@@SAXXZ
void FURL::StaticExit() {}

// ?StaticInit@FURL@@SAXXZ
void FURL::StaticInit() {}

// ?Pad16Bit@FWaveModInfo@@QAEKK@Z
DWORD FWaveModInfo::Pad16Bit(DWORD p0) { return 0; }

// ?GetOption@FURL@@QBEPBGPBG0@Z
const TCHAR* FURL::GetOption(const TCHAR* p0, const TCHAR* p1) const { return NULL; }

// ??1FCollisionHash@@UAE@XZ
FCollisionHash::~FCollisionHash() {}

// ??1FCollisionOctree@@UAE@XZ
FCollisionOctree::~FCollisionOctree() {}

// ??1FLevelSceneNode@@UAE@XZ
FLevelSceneNode::~FLevelSceneNode() {}

// ??1FMatineeTools@@UAE@XZ
FMatineeTools::~FMatineeTools() {}

// ??1FSceneNode@@UAE@XZ
FSceneNode::~FSceneNode() {}

// ?GetActorSceneNode@FSceneNode@@UAEPAVFActorSceneNode@@XZ
FActorSceneNode * FSceneNode::GetActorSceneNode() { return NULL; }

// ?GetCameraSceneNode@FSceneNode@@UAEPAVFCameraSceneNode@@XZ
FCameraSceneNode * FSceneNode::GetCameraSceneNode() { return NULL; }

// ?GetLevelSceneNode@FSceneNode@@UAEPAVFLevelSceneNode@@XZ
FLevelSceneNode * FSceneNode::GetLevelSceneNode() { return NULL; }

// ?MeshToWorld@UMeshInstance@@UAE?AVFMatrix@@XZ
FMatrix UMeshInstance::MeshToWorld() { return FMatrix(); }

// ?GetMirrorSceneNode@FSceneNode@@UAEPAVFMirrorSceneNode@@XZ
FMirrorSceneNode * FSceneNode::GetMirrorSceneNode() { return NULL; }

// ?GetSkySceneNode@FSceneNode@@UAEPAVFSkySceneNode@@XZ
FSkySceneNode * FSceneNode::GetSkySceneNode() { return NULL; }

// ?GetWarpZoneSceneNode@FSceneNode@@UAEPAVFWarpZoneSceneNode@@XZ
FWarpZoneSceneNode * FSceneNode::GetWarpZoneSceneNode() { return NULL; }

// ?GetMovement@UMeshAnimation@@UAEPAVMotionChunk@@VFName@@@Z
MotionChunk * UMeshAnimation::GetMovement(FName p0) { return NULL; }

// ?FillVertexBuffer@USpriteEmitter@@UAEHPAVFSpriteParticleVertex@@PAVFLevelSceneNode@@@Z
int USpriteEmitter::FillVertexBuffer(FSpriteParticleVertex * p0, FLevelSceneNode * p1) { return 0; }

// ?ActorEncroachmentCheck@FCollisionHash@@UAEPAUFCheckResult@@AAVFMemStack@@PAVAActor@@VFVector@@VFRotator@@KK@Z
FCheckResult * FCollisionHash::ActorEncroachmentCheck(FMemStack & p0, AActor * p1, FVector p2, FRotator p3, DWORD p4, DWORD p5) { return NULL; }

// ?ActorLineCheck@FCollisionHash@@UAEPAUFCheckResult@@AAVFMemStack@@VFVector@@11KKPAVAActor@@@Z
FCheckResult * FCollisionHash::ActorLineCheck(FMemStack & p0, FVector p1, FVector p2, FVector p3, DWORD p4, DWORD p5, AActor * p6) { return NULL; }

// ?ActorOverlapCheck@FCollisionHash@@UAEPAUFCheckResult@@AAVFMemStack@@PAVAActor@@PAVFBox@@H@Z
FCheckResult * FCollisionHash::ActorOverlapCheck(FMemStack & p0, AActor * p1, FBox * p2, int p3) { return NULL; }

// ?ActorPointCheck@FCollisionHash@@UAEPAUFCheckResult@@AAVFMemStack@@VFVector@@1KKHPAVAActor@@@Z
FCheckResult * FCollisionHash::ActorPointCheck(FMemStack & p0, FVector p1, FVector p2, DWORD p3, DWORD p4, int p5, AActor * p6) { return NULL; }

// ?ActorRadiusCheck@FCollisionHash@@UAEPAUFCheckResult@@AAVFMemStack@@VFVector@@MK@Z
FCheckResult * FCollisionHash::ActorRadiusCheck(FMemStack & p0, FVector p1, float p2, DWORD p3) { return NULL; }

// ?ActorEncroachmentCheck@FCollisionOctree@@UAEPAUFCheckResult@@AAVFMemStack@@PAVAActor@@VFVector@@VFRotator@@KK@Z
FCheckResult * FCollisionOctree::ActorEncroachmentCheck(FMemStack & p0, AActor * p1, FVector p2, FRotator p3, DWORD p4, DWORD p5) { return NULL; }

// ?ActorLineCheck@FCollisionOctree@@UAEPAUFCheckResult@@AAVFMemStack@@VFVector@@11KKPAVAActor@@@Z
FCheckResult * FCollisionOctree::ActorLineCheck(FMemStack & p0, FVector p1, FVector p2, FVector p3, DWORD p4, DWORD p5, AActor * p6) { return NULL; }

// ?ActorOverlapCheck@FCollisionOctree@@UAEPAUFCheckResult@@AAVFMemStack@@PAVAActor@@PAVFBox@@H@Z
FCheckResult * FCollisionOctree::ActorOverlapCheck(FMemStack & p0, AActor * p1, FBox * p2, int p3) { return NULL; }

// ?ActorPointCheck@FCollisionOctree@@UAEPAUFCheckResult@@AAVFMemStack@@VFVector@@1KKHPAVAActor@@@Z
FCheckResult * FCollisionOctree::ActorPointCheck(FMemStack & p0, FVector p1, FVector p2, DWORD p3, DWORD p4, int p5, AActor * p6) { return NULL; }

// ?ActorRadiusCheck@FCollisionOctree@@UAEPAUFCheckResult@@AAVFMemStack@@VFVector@@MK@Z
FCheckResult * FCollisionOctree::ActorRadiusCheck(FMemStack & p0, FVector p1, float p2, DWORD p3) { return NULL; }

// ?getKConstraint@AKConstraint@@UBEPAUMdtBaseConstraint@@XZ
MdtBaseConstraint * AKConstraint::getKConstraint() const { return NULL; }

// ?AddActor@FCollisionHash@@UAEXPAVAActor@@@Z
void FCollisionHash::AddActor(AActor * p0) {}

// ?CheckActorLocations@FCollisionHash@@UAEXPAVULevel@@@Z
void FCollisionHash::CheckActorLocations(ULevel * p0) {}

// ?CheckActorNotReferenced@FCollisionHash@@UAEXPAVAActor@@@Z
void FCollisionHash::CheckActorNotReferenced(AActor * p0) {}

// ?CheckIsEmpty@FCollisionHash@@UAEXXZ
void FCollisionHash::CheckIsEmpty() {}

// ?RemoveActor@FCollisionHash@@UAEXPAVAActor@@@Z
void FCollisionHash::RemoveActor(AActor * p0) {}

// ?Tick@FCollisionHash@@UAEXXZ
void FCollisionHash::Tick() {}

// ?AddActor@FCollisionOctree@@UAEXPAVAActor@@@Z
void FCollisionOctree::AddActor(AActor * p0) {}

// ?CheckActorLocations@FCollisionOctree@@UAEXPAVULevel@@@Z
void FCollisionOctree::CheckActorLocations(ULevel * p0) {}

// ?CheckActorNotReferenced@FCollisionOctree@@UAEXPAVAActor@@@Z
void FCollisionOctree::CheckActorNotReferenced(AActor * p0) {}

// ?CheckIsEmpty@FCollisionOctree@@UAEXXZ
void FCollisionOctree::CheckIsEmpty() {}

// ?RemoveActor@FCollisionOctree@@UAEXPAVAActor@@@Z
void FCollisionOctree::RemoveActor(AActor * p0) {}

// ?Tick@FCollisionOctree@@UAEXXZ
void FCollisionOctree::Tick() {}

// ?MeshBuildBounds@UMeshInstance@@UAEXXZ
void UMeshInstance::MeshBuildBounds() {}

// ?ChangeOrientation@ASceneManager@@QAEXUFOrientation@@@Z
void ASceneManager::ChangeOrientation(FOrientation p0) {}

// ?m_vStartLipsynch@ECLipSynchData@@QAEXXZ
void ECLipSynchData::m_vStartLipsynch() {}

// ?m_vStopLipsynch@ECLipSynchData@@QAEXXZ
void ECLipSynchData::m_vStopLipsynch() {}

// ?m_vUpdateBonesCompressed@ECLipSynchData@@QAEXH@Z
void ECLipSynchData::m_vUpdateBonesCompressed(int p0) {}

// ?m_vUpdateBonesCompressed_BoneView@ECLipSynchData@@QAEXH@Z
void ECLipSynchData::m_vUpdateBonesCompressed_BoneView(int p0) {}

// ?m_vUpdateBonesCompressed_PhonemsSeq@ECLipSynchData@@QAEXH@Z
void ECLipSynchData::m_vUpdateBonesCompressed_PhonemsSeq(int p0) {}

// ?m_vUpdateLipSynch@ECLipSynchData@@QAEXM@Z
void ECLipSynchData::m_vUpdateLipSynch(float p0) {}

// ?GetActorExtent@FCollisionHash@@QAEXPAVAActor@@AAH11111@Z
void FCollisionHash::GetActorExtent(AActor * p0, int & p1, int & p2, int & p3, int & p4, int & p5, int & p6) {}

// ?GetHashIndices@FCollisionHash@@QAEXVFVector@@AAH11@Z
void FCollisionHash::GetHashIndices(FVector p0, int & p1, int & p2, int & p3) {}

// ?GetSamples@FMatineeTools@@QAEXPAVASceneManager@@PAVUMatAction@@PAV?$TArray@VFVector@@@@@Z
void FMatineeTools::GetSamples(ASceneManager * p0, UMatAction * p1, TArray<FVector> * p2) {}

// ?Init@FMatineeTools@@QAEXXZ
void FMatineeTools::Init() {}

// ?ActorEncroachmentCheck@FOctreeNode@@QAEXPAVFCollisionOctree@@PBVFPlane@@@Z
void FOctreeNode::ActorEncroachmentCheck(FCollisionOctree * p0, FPlane const * p1) {}

// ?ActorNonZeroExtentLineCheck@FOctreeNode@@QAEXPAVFCollisionOctree@@PBVFPlane@@@Z
void FOctreeNode::ActorNonZeroExtentLineCheck(FCollisionOctree * p0, FPlane const * p1) {}

// ?ActorOverlapCheck@FOctreeNode@@QAEXPAVFCollisionOctree@@PBVFPlane@@@Z
void FOctreeNode::ActorOverlapCheck(FCollisionOctree * p0, FPlane const * p1) {}

// ?ActorPointCheck@FOctreeNode@@QAEXPAVFCollisionOctree@@PBVFPlane@@PAVAActor@@@Z
void FOctreeNode::ActorPointCheck(FCollisionOctree * p0, FPlane const * p1, AActor * p2) {}

// ?ActorRadiusCheck@FOctreeNode@@QAEXPAVFCollisionOctree@@PBVFPlane@@@Z
void FOctreeNode::ActorRadiusCheck(FCollisionOctree * p0, FPlane const * p1) {}

// ?ActorZeroExtentLineCheck@FOctreeNode@@QAEXPAVFCollisionOctree@@MMMMMMPBVFPlane@@@Z
void FOctreeNode::ActorZeroExtentLineCheck(FCollisionOctree * p0, float p1, float p2, float p3, float p4, float p5, float p6, FPlane const * p7) {}

// ?CheckActorNotReferenced@FOctreeNode@@QAEXPAVAActor@@@Z
void FOctreeNode::CheckActorNotReferenced(AActor * p0) {}

// ?CheckIsEmpty@FOctreeNode@@QAEXXZ
void FOctreeNode::CheckIsEmpty() {}

// ?Draw@FOctreeNode@@QAEXVFColor@@HPBVFPlane@@@Z
void FOctreeNode::Draw(FColor p0, int p1, FPlane const * p2) {}

// ?DrawFlaggedActors@FOctreeNode@@QAEXPAVFCollisionOctree@@PBVFPlane@@@Z
void FOctreeNode::DrawFlaggedActors(FCollisionOctree * p0, FPlane const * p1) {}

// ?FilterTest@FOctreeNode@@QAEXPAVFBox@@HPAV?$TArray@PAVFOctreeNode@@@@PBVFPlane@@@Z
void FOctreeNode::FilterTest(FBox * p0, int p1, TArray<FOctreeNode *> * p2, FPlane const * p3) {}

// ?MultiNodeFilter@FOctreeNode@@QAEXPAVAActor@@PAVFCollisionOctree@@PBVFPlane@@@Z
void FOctreeNode::MultiNodeFilter(AActor * p0, FCollisionOctree * p1, FPlane const * p2) {}

// ?RemoveAllActors@FOctreeNode@@QAEXPAVFCollisionOctree@@@Z
void FOctreeNode::RemoveAllActors(FCollisionOctree * p0) {}

// ?SingleNodeFilter@FOctreeNode@@QAEXPAVAActor@@PAVFCollisionOctree@@PBVFPlane@@@Z
void FOctreeNode::SingleNodeFilter(AActor * p0, FCollisionOctree * p1, FPlane const * p2) {}

// ?BuildActionSpotList@FPathBuilder@@QAEXPAVULevel@@@Z
void FPathBuilder::BuildActionSpotList(ULevel * p0) {}

// ?ReviewPaths@FPathBuilder@@QAEXPAVULevel@@@Z
void FPathBuilder::ReviewPaths(ULevel * p0) {}

// ?defineChangedPaths@FPathBuilder@@QAEXPAVULevel@@@Z
void FPathBuilder::defineChangedPaths(ULevel * p0) {}

// ?definePaths@FPathBuilder@@QAEXPAVULevel@@@Z
void FPathBuilder::definePaths(ULevel * p0) {}

// ?undefinePaths@FPathBuilder@@QAEXPAVULevel@@@Z
void FPathBuilder::undefinePaths(ULevel * p0) {}

// ?Init@FPoly@@QAEXXZ
void FPoly::Init() {}

// ?InsertVertex@FPoly@@QAEXHVFVector@@@Z
void FPoly::InsertVertex(int p0, FVector p1) {}

// ?Reverse@FPoly@@QAEXXZ
void FPoly::Reverse() {}

// ?SplitInHalf@FPoly@@QAEXPAV1@@Z
void FPoly::SplitInHalf(FPoly * p0) {}

// ?Transform@FPoly@@QAEXABVFModelCoords@@ABVFVector@@1M@Z
void FPoly::Transform(FModelCoords const & p0, FVector const & p1, FVector const & p2, float p3) {}

// ?Delete@FRebuildTools@@QAEXVFString@@@Z
void FRebuildTools::Delete(FString p0) {}

// ?Init@FRebuildTools@@QAEXXZ
void FRebuildTools::Init() {}

// ?SetCurrent@FRebuildTools@@QAEXVFString@@@Z
void FRebuildTools::SetCurrent(FString p0) {}

// ?Shutdown@FRebuildTools@@QAEXXZ
void FRebuildTools::Shutdown() {}

// ?AddDataPoint@FStatGraph@@QAEXVFString@@MH@Z
void FStatGraph::AddDataPoint(FString p0, float p1, int p2) {}

// ?AddLine@FStatGraph@@QAEXVFString@@VFColor@@MM@Z
void FStatGraph::AddLine(FString p0, FColor p1, float p2, float p3) {}

// ?AddLineAutoRange@FStatGraph@@QAEXVFString@@VFColor@@@Z
void FStatGraph::AddLineAutoRange(FString p0, FColor p1) {}

// ?Render@FStatGraph@@QAEXPAVUViewport@@PAVFRenderInterface@@@Z
void FStatGraph::Render(UViewport * p0, FRenderInterface * p1) {}

// ?Reset@FStatGraph@@QAEXXZ
void FStatGraph::Reset() {}

// ?AddOption@FURL@@QAEXPBG@Z
void FURL::AddOption(const TCHAR* p0) {}

// ?LoadURLConfig@FURL@@QAEXPBG0@Z
void FURL::LoadURLConfig(const TCHAR* p0, const TCHAR* p1) {}

// ?SaveURLConfig@FURL@@QBEXPBG00@Z
void FURL::SaveURLConfig(const TCHAR* p0, const TCHAR* p1, const TCHAR* p2) const {}

// ?HalveData@FWaveModInfo@@QAEXXZ
void FWaveModInfo::HalveData() {}

// ?HalveReduce16to8@FWaveModInfo@@QAEXXZ
void FWaveModInfo::HalveReduce16to8() {}

// ?NoiseGateFilter@FWaveModInfo@@QAEXXZ
void FWaveModInfo::NoiseGateFilter() {}

// ?Reduce16to8@FWaveModInfo@@QAEXXZ
void FWaveModInfo::Reduce16to8() {}

// ?AVIStart@@YAXPBGPAVUEngine@@H@Z
void AVIStart(const TCHAR* p0, UEngine * p1, int p2) {}

// ?AVIStop@@YAXXZ
void AVIStop() {}

// ?AVITakeShot@@YAXPAVUEngine@@@Z
void AVITakeShot(UEngine * p0) {}

// ?DrawSprite@@YAXPAVAActor@@VFVector@@PAVUMaterial@@PAVFLevelSceneNode@@PAVFRenderInterface@@@Z
void DrawSprite(AActor * p0, FVector p1, UMaterial * p2, FLevelSceneNode * p3, FRenderInterface * p4) {}

// ?DrawSprite@@YAXMVFVector@@0PAVUMaterial@@VFPlane@@EPAVFCameraSceneNode@@PAVFRenderInterface@@MHH@Z
void DrawSprite(float p0, FVector p1, FVector p2, UMaterial * p3, FPlane p4, BYTE p5, FCameraSceneNode * p6, FRenderInterface * p7, float p8, int p9, int p10) {}

// ?KME2UPosition@@YAXPAVFVector@@QBM@Z
void KME2UPosition(FVector * p0, float const * const p1) {}

// ?KME2UVecCopy@@YAXPAVFVector@@QBM@Z
void KME2UVecCopy(FVector * p0, float const * const p1) {}

// ?KTermGameKarma@@YAXXZ
void KTermGameKarma() {}

// ?KU2MEPosition@@YAXQAMVFVector@@@Z
void KU2MEPosition(float * const p0, FVector p1) {}

// ?KU2MEVecCopy@@YAXQAMVFVector@@@Z
void KU2MEVecCopy(float * const p0, FVector p1) {}

// ?KUpdateMassProps@@YAXPAVUKMeshProps@@@Z
void KUpdateMassProps(UKMeshProps * p0) {}

// ?KarmaTriListDataInit@@YAXPAU_KarmaTriListData@@@Z
void KarmaTriListDataInit(_KarmaTriListData * p0) {}

// =============================================================================
// Explicit template instantiation for TArray<BYTE> and TLazyArray<BYTE>.
// The retail Engine.dll exports these symbols; explicit instantiation forces the
// compiler to emit out-of-line copies of all inline template members.
// =============================================================================
template class TArray<BYTE>;
template class TLazyArray<BYTE>;
