// EngineStubs4.cpp - Linker stub directives (chunk 4 of 4)
// Maps unresolved .def exports to dummy implementations

#pragma comment(linker, "/alternatename:?GetInputAction@UInput@@QAE?AW4EInputAction@@XZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetInputDelta@UInput@@QAEMXZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetKeyName@UInput@@UBEPBGW4EInputKey@@@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetLocalVertex@UTerrainSector@@QAEHHH@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetMirrorSceneNode@FMirrorSceneNode@@UAEPAV1@XZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetMovement@UMeshAnimation@@UAEPAVMotionChunk@@VFName@@@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetOptimizedRepList@AGameReplicationInfo@@UAEPAHPAEPAUFPropertyRetirement@@PAHPAVUPackageMap@@PAVUActorChannel@@@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetOptimizedRepList@ALevelInfo@@UAEPAHPAEPAUFPropertyRetirement@@PAHPAVUPackageMap@@PAVUActorChannel@@@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetOptimizedRepList@APlayerReplicationInfo@@UAEPAHPAEPAUFPropertyRetirement@@PAHPAVUPackageMap@@PAVUActorChannel@@@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetPeriod@FSoundData@@QAEMXZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetPhysicsVolume@ALevelInfo@@QAEPAVAPhysicsVolume@@VFVector@@PAVAActor@@H@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetRenderBoundingBox@UTerrainPrimitive@@QAE?AVFBox@@PBVAActor@@H@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetSkySceneNode@FSkySceneNode@@UAEPAV1@XZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetViewFrustum@FDirectionalLightMapSceneNode@@UAE?AVFConvexVolume@@XZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetViewFrustum@FLevelSceneNode@@UAE?AVFConvexVolume@@XZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetViewFrustum@FPointLightMapSceneNode@@UAE?AVFConvexVolume@@XZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?GetWarpZoneSceneNode@FWarpZoneSceneNode@@UAEPAV1@XZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?HandleClientPlayer@UDemoRecConnection@@UAEXPAVAPlayerController@@@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?Illuminate@UTerrainPrimitive@@UAEXPAVAActor@@H@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?Init@FEngineStats@@QAEXXZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?InitGameInfoGameService@AGameInfo@@UAEXXZ=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?IsCoplanar@FPoly@@QBEHABV1@@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?IsNetReady@UDemoRecConnection@@UAEHH@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?IsSectorAll@UTerrainSector@@QAEHHE@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?IsSoundAudibleFromZone@ALevelInfo@@QAEHHH@Z=_dummy_stub_func")
#pragma comment(linker, "/alternatename:?IsTriangleAll@UTerrainSector@@QAEHHHHHHE@Z=_dummy_stub_func")
